---
- name: Deploy app on Ec2 instance
  hosts: webserver
  become: true
  #user: ubuntu
  #sudo: yes
  gather_facts: no
  tasks:
  - name: Pull app source code from repo
    git:
      repo: https://github.com/juanjopb/vanhacktest.git
      dest: /opt
  
  - name: Update linux
    become: True
    become_method: sudo
    remote_user: ubuntu
    raw: apt update  && apt install -y python3 python3-pi
  
  - name: Install Flask
    become: True
    become_method: sudo
    remote_user: ubuntu
    pip:
      name: 
        - flask
        -  ansible
      state: latest
  
  - name: Running python app
    become: True
    become_method: sudo
    remote_user: ubuntu
    shell: nohup python3 /opt/vanhacktest/FlaskApp/app.py &

#- name: Copy startup script to /opt directory of EC2 instance
#  copy:
#  src: ./startup.sh
#  dest: /opt/startup.sh
#  mode: 0755

#- name: Copy file with owner and permissions
#  copy:
#    src: /srv/myfiles/foo.conf
#    dest: /etc/foo.conf
#    owner: foo
#    group: foo
#    mode: '0644'

#- name: Run startup script
#  shell: ./startup.sh &
#  args:
#    chdir: /opt
#  async: 45
#  poll: 0