- name: Pull app source code from GIT
  git:
    repo: https://github.com/juanjopb/vanhacktest.git
    dest: /opt

- name: Update linux
  #become: True
  #become_method: sudo
  #remote_user: ubuntu
  raw: apt update  && apt install -y python3 python3-pip

- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python3-mysqldb
    - python-mysqldb
    - mysql-client 
    - libmysqlclient-dev
    - build-essential 
    - libssl-dev 
    - libffi-dev 
    - python3-dev

- name: Make sure pymysql is present
  #become: true # needed if the other tasks are not played as root
  pip:
    name: PyMySQL
    state: present

- name:  Create MySQL database
  mysql_db:
    login_host:      "{{ rds_endpoint }}"
    login_user:      "{{ rds_username }}"
    login_password:  "{{ rds_password }}"
    name:            "{{ rds_db_name }}"
    state:           present

- name: Copy SQL file to EC2 Server
  copy: 
    src: "./files/create_table.sql"
    dest: "/opt/create_table.sql" 
    mode: 0600
  #when: ec2_keypair.changed

- name:  Create MySQL database table
  mysql_db:
    login_host:      "{{ rds_endpoint }}"
    login_user:      "{{ rds_username }}"
    login_password:  "{{ rds_password }}"
    name:            "{{ rds_db_name }}"
    state:           import
    target: "/opt/create_table.sql"

- name: Register Environment Variables
  shell: "export VAR_MYSQL_HOST={{ rds_endpoint }}"
  #environment:
  #  VAR_MYSQL_HOST: "{{ rds_endpoint }}"
  #  VAR_MYSQL_USER: "{{ rds_username }}"
  #  VAR_MYSQL_PASSWORD: "{{ rds_password }}"
  #  VAR_MYSQL_DB: "{{ rds_db_name }}"

- name: Create .sh with environment Variables
  #become_method: sudo
  #remote_user: ubuntu
  copy:
    mode: 0600
    dest: "/opt/mysql_vars.yaml"
    content: |
      VAR_MYSQL_HOST: {{ rds_endpoint }}
      VAR_MYSQL_USER: {{ rds_username }}
      VAR_MYSQL_PASSWORD: {{ rds_password }}
      VAR_MYSQL_DB: {{ rds_db_name }}

- name: Execute the script
  command: sh /opt/var_mysql.sh

- name: Install Flask and dependencies
  #become: True
  #become_method: sudo
  #remote_user: ubuntu
  pip:
    name: 
      - flask
      - flask_mysql
      - flask_table
      - flask_mysqldb
      - pyyaml
    state: latest

- name: Running python app
  #become: True
  #become_method: sudo
  #remote_user: ubuntu
  shell: nohup python3 /opt/FlaskApp/app.py &
